version: "3.8"

services:
  postgres:
    container_name: "painel-infinity"
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: infinity
